version: '3.8'

services:
  go-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: develop
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./backend:/go/src
    
  db:
    image: mysql:8.0
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Tokyo
    volumes:
      - gin_mysql_volume:/var/lib/mysql

volumes:
  gin_mysql_volume:
    name: gin_mysql_volume
    external: true
