version: '3.8'

services:
  go:
    build:
      context: .
      dockerfile: ./.docker/goapp/Dockerfile
      target: develop
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./backend:/go/src
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    
  db:
    image: mysql:8.0
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ./.docker/mysql/.env_mysql
    volumes:
      - ./.docker/mysql/my.cnf:/etc/my.cnf
      - gin_mysql_volume:/var/lib/mysql

volumes:
  gin_mysql_volume:
    name: gin_mysql_volume
    external: true
